image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean compile

test:
  stage: test
  tags:
    - ugrad
  script:
    - mvn clean test

install:
  stage: install
  tags:
    - ugrad
  script:
    - mvn clean test -DskipTests=true
